### ISSUE TITLE
Bug: Remove filter again (container.filters = null) throws error

### ISSUE THREAD

**Issue by Matt-Maerz** [pixijs/pixi.js#10449]
### Current Behavior
Remove filter again (container.filters = null) throws error
```
loaders.mjs:1063 Uncaught TypeError: Cannot read properties of null (reading 'length')
    at FilterSystem.push (loaders.mjs:1063:1)
    at FilterPipe.execute (loaders.mjs:919:30)
    at executeInstructions (filter-color-matrix.mjs:468:1)
    at RenderGroupPipe.execute (filter-color-matrix.mjs:488:1)
    at executeInstructions (filter-color-matrix.mjs:468:1)
    at RenderGroupSystem.render (filter-fxaa.mjs:36:7)
    at SystemRunner.emit (loaders.mjs:1423:1)
    at WebGPURenderer.render (loaders.mjs:1589:27)
    at Number.tickerAnimate (InitGame.js:829:14)
    at TickerListener.emit (utils.mjs:581:1)
```
### Expected Behavior

The filter should disappear from the Container

### Steps to Reproduce
```js
renderer = new PIXI.WebGPURenderer();
    await renderer.init({
        width: 1920,
        height: 1080,
        background: 0x000000
  });
let blurFilter = new PIXI.BlurFilter({strength: 8, quality: 4});
tempContainer.filters = [blurFilter];
// ....
tempContainer.filters = null
```

### Environment

- **pixi.js version 8.1.0**
- **Browser Version 119.0.6045.200**:
- **Windows Version 11 Home 23H2**:

### Possible Solution

-

### Additional Information

-

**Comment by evan00144** [comment]
any update?

**Comment by Matt-Maerz** [comment]
Workaround: 
1. "..filters[i].enable= false" across all filters
2. "....filters = null"

**Comment by GoodBoyDigital** [comment]
heya @evan00144 , could you test the latest version pls?

**Comment by Matt-Maerz** [comment]
> heya @Matt-Maerz , could you test the latest version pls?

Hey @GoodBoyDigital, thanks for your reply.
Unfortunately, the problem also exists with version 8.1.3
I'm sorry.

**Comment by GoodBoyDigital** [comment]
hey @Matt-Maerz , can't seem to recreate this one? Would you mind providing a little playground pls? thanks!

**Comment by Matt-Maerz** [comment]
> hey @Matt-Maerz , can't seem to recreate this one? Would you mind providing a little playground pls? thanks!

Hey @GoodBoyDigital, 
thanks for your reply and sorry for the delay.

I have now made you an example and I think it has something to do with the isRenderGroup: true
Bug have a look.

You can use the zip. But i know, it is a Zip file:
[filtersNullProblem.zip](https://github.com/user-attachments/files/15749253/filtersNullProblem.zip)

Alternatively, here are the files. Simply always remove the .txt extension at the end 
[index.html.txt](https://github.com/user-attachments/files/15749256/index.html.txt)
[main.js.txt](https://github.com/user-attachments/files/15749257/main.js.txt)
[pixi_v816.js.txt](https://github.com/user-attachments/files/15749258/pixi_v816.js.txt)
[pixi-filters.js.txt](https://github.com/user-attachments/files/15749259/pixi-filters.js.txt)
[tree.png.txt](https://github.com/user-attachments/files/15749260/tree.png.txt)

Thanks for your time.
Best regards
Matt

**Comment by Zyie** [comment]
Thanks for reporting this issue!

It looks like the problem has been resolved and things should now be working as expected.
If you’re still seeing any issues or have related questions, feel free to comment and we’ll take another look.
