### ISSUE TITLE
Rendering a cloned Graphics on the WebGL renderer object causes an error

### ISSUE THREAD

**Issue by lexi-lambda** [pixijs/pixi.js#2003]
When I create a `PIXI.Graphics` object and `.clone()` it, then attempt to render it, I receive the following error:

```
TypeError: Cannot read property 'data' of undefined
    at i.render (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.7/pixi.min.js:19:45866)
    at k._renderWebGL (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.7/pixi.min.js:19:41178)
    at k.e.renderWebGL (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.7/pixi.min.js:19:31787)
    at e.renderWebGL (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.7/pixi.min.js:19:31860)
    at n.renderDisplayObject (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.7/pixi.min.js:19:90794)
    at n.render (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.7/pixi.min.js:19:90613)
```

I only seem to get the error if the *original* Graphics object has already been rendered before. If I clone an unrendered object, the error doesn't occur.

See [an example on JSBin here](http://jsbin.com/xememejeli/1/edit?js,output).

**Comment by englercj** [comment]
Interesting, thanks for the report

**Comment by lexi-lambda** [comment]
thanks! :+1:
