### ISSUE TITLE
Babel Node ES6 Webpack: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by rochestb** [pixijs/pixi.js#2296]
```/node_modules/pixi.js/src/core/text/Text.js:94
Text.fontPropertiesCanvas = document.createElement('canvas');
                            ^

ReferenceError: document is not defined
    at Object.<anonymous> (/node_modules/pixi.js/src/core/text/Text.js:94:29)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/node_modules/pixi.js/src/core/index.js:28:29)
    at Module._compile (module.js:425:26)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.1.1/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@1.0.0 dev: `babel-node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@1.0.0 dev script 'babel-node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

```

` import PIXI from 'pixi.js'; `

```
'use strict';

var webpack = require('webpack');
var autoprefixer = require('autoprefixer');
var WebpackErrorNotificationPlugin = require('webpack-error-notification');
var ModernizrWebpackPlugin = require('modernizr-webpack-plugin');
var hmrConfig = require('./hmr.config'); 
var modernizrConfig = require('./modernizr.config');
var path = require('path');

var ROOT_PATH = path.resolve(__dirname);
var BUILD_PATH = path.resolve(ROOT_PATH, '../public/dist');
var APP_PATH = path.resolve(ROOT_PATH, '../app');
var host = process.env.HOST || "0.0.0.0";
var port = process.env.PORT || 3000;

var config = {
  context: APP_PATH,
  devtool: 'eval-source-map',
  entry: {
    app: [
      'eventsource-polyfill', // necessary for hot reloading with IE
      'webpack-hot-middleware/client',
      APP_PATH + '/app.js'
    ]
  },
  output: {
    path: BUILD_PATH,
    publicPath: 'http://' + host + ':' + port + '/dist',
    filename: 'app.js'
  },

  resolve: {
    extensions: ['', '.js', '.jsx', '.scss'],
    root: APP_PATH
  },

  module: {
    noParse: [ /.*(pixi\.js).*/ ],
    loaders: [
      {
        test: /\.js?$|\.jsx?$/,
        loaders: ['babel?' + JSON.stringify(hmrConfig), 'eslint']
      },
      {
        test: /\.json$/,
        include: path.join(__dirname, 'node_modules', 'pixi.js'),
      },
      {
        test: /\.scss$/,
        loaders: ['style', 'css', 'postcss', 'sass?outputStyle=expanded&sourceMap=true&sourceMapContents=true']
      },
      { 
        test: /\.(jpg|jpeg|png|gif|svg)$/, 
        loaders: ['url?limit=25000', 'img']
      },
      {
        test: /\.(eot|woff|woff2|ttf|svg)$/, 
        loader: 'url?limit=20000'
      }
    ]
  },

  postLoaders: [
    {
      loader: 'transform?brfs'
    }
  ],

  plugins: [
    new webpack.DefinePlugin({
      "process.env": {
        BROWSER: JSON.stringify(true)
      }
    }),
    new ModernizrWebpackPlugin(modernizrConfig),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new WebpackErrorNotificationPlugin()
  ],
  postcss: [
    autoprefixer({
      browsers: ['last 2 versions']
    })
  ]
};

module.exports = config;
```

**Comment by englercj** [comment]
Correct, pixi uses DOM objects that do not exist in node.
