### ISSUE TITLE
Cannot add resources while the loader is running.

### ISSUE THREAD

**Issue by Milewski** [pixijs/pixi.js#3733]
There is absolutely no error, everything works just as expected.. however in the console i always get this error

```
Uncaught Error: Cannot add resources while the loader is running.
    at Loader.add (http://192.168.1.227:8080/js/vendor.c989d89926bfe7181186.js:5832:19)
    at http://192.168.1.227:8080/js/animation.c989d89926bfe7181186.js:18569:79
    at Array.forEach (native)
    at Animation.init (http://192.168.1.227:8080/js/animation.c989d89926bfe7181186.js:18569:28)
    at new Animation (http://192.168.1.227:8080/js/animation.c989d89926bfe7181186.js:18556:14)
    at Object.module.exports (http://192.168.1.227:8080/js/animation.c989d89926bfe7181186.js:18634:21)
    at __webpack_require__ (http://192.168.1.227:8080/js/vendor.c989d89926bfe7181186.js:692:30)
    at fn (http://192.168.1.227:8080/js/vendor.c989d89926bfe7181186.js:111:20)
    at Object.module.exports (http://192.168.1.227:8080/js/animation.c989d89926bfe7181186.js:31941:18)
    at __webpack_require__ (http://192.168.1.227:8080/js/vendor.c989d89926bfe7181186.js:692:30)
```

and the code i use to load all the assets is this one

```js

images.forEach(image => Loader.add(image));

Loader
.add('background-clouds.jpg', backgroundClouds)
.add({
    name: 'animation-sprite.png',
    url: animationSprite,

    /**
     * Parse, it will be automatically saved into the cache, for use later
     */
    onComplete: resource => {
        new PIXI.Spritesheet(resource.texture, require('../build/animation-sprite.json')).parse(() => {});
    }

})
.load(loader => this.setup(loader))
.on('progress', loader => this.loading.progress(Math.round(loader.progress)))
.on('complete', loader => this.loading.complete());
```

I'm assuming the loader will start loading whenever i call `.load()` as this code above runs sync i don't see any way it would trigger `.load` first than `.add`... but stills get the error shown on console...

**Comment by uorbe001** [comment]
We had a similar issue with pixi-packer which I fixed by adding the parentResource property on our parser, but spritesheetParser is already doing that. What version of pixi are you using?

**Comment by Milewski** [comment]
i'm using version `4.3.5`, or to be more precise .. this commit  2973473fd5f6412434a27737d29eea040a9082e3

I have tried leaving only one `.add`  to the loader... but still have the same problem.. removing that section where i `.add()` `animation-sprite.png` also doesn't seen to fix the issue.

**Comment by Milewski** [comment]
This issue can be close.. the reason why i had it loading twice was i had a file that was being shared with two separated bundles... something like this

```
module-1.js
   -> helpers.js

module-2.js
   -> helpers.js

....

<script src='module-1.js'></script>
<script src='module-2.js'></script>
```

so in another words.. helpers was being bundled twice .. hence the duplication... my bad..
