### ISSUE TITLE
There is always an error when `npm run test`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3757]
```
2) PIXI renders should draw a rectangle:
     AssertionError: WebGL results do not match.
      at renderer.compare (/Users/rocky/DEV/@git-fav/_pixijs.com/pixi.js/test/renders/index.js:20:21)
      at run (/Users/rocky/DEV/@git-fav/_pixijs.com/pixi.js/test/renders/lib/Renderer.js:211:17)
      at done (/Users/rocky/DEV/@git-fav/_pixijs.com/pixi.js/test/renders/lib/Renderer.js:168:21)
```

I test the `pixi.js dev` ,not my fork version.

**Comment by Dimous** [comment]
#3741

**Comment by finscn** [comment]
@Dimous , thanks.
