### ISSUE TITLE
Sprite.texture = null --> error

### ISSUE THREAD

**Issue by tconkling** [pixijs/pixi.js#4958]
Setting a Sprite's `texture` to `null` results in errors when calculating bounds:

```
let sprite = new Sprite();
sprite.texture = null;
let r = sprite.getLocalBounds(); // TypeError: Cannot read property 'trim' of null
```

The error is thrown in `Sprite._calculateBounds`, which accesses properties on `Sprite._texture`:

```
Uncaught error TypeError: Cannot read property 'trim' of null
    at Sprite._calculateBounds (http://localhost:63342/eternajs/dist/dev/main.js:47207:34)
    at Sprite.calculateBounds (http://localhost:63342/eternajs/dist/dev/main.js:34654:14)
    at Container.calculateBounds (http://localhost:63342/eternajs/dist/dev/main.js:34663:19)
    at Container.getBounds (http://localhost:63342/eternajs/dist/dev/main.js:35155:18)
    at Container.getLocalBounds (http://localhost:63342/eternajs/dist/dev/main.js:35192:27)
```

### Possible Solution

Either throw an Error immediately if a Sprite's texture is set to null, or coerce null textures to `Texture.EMPTY` in `Sprite.set texture()`?

### Environment

- `pixi.js` version: 4.8.1
- Browser: Chrome 66
- Device: Desktop

**Comment by finscn** [comment]
You should use 
`sprite.texture = PIXI.Texture.EMPTY` instead of `sprite.texture = null`

But I think maybe we should update the Sprite.js code , like this: 
```
    set texture(value) // eslint-disable-line require-jsdoc
    {
        if (this._texture === value)
        {
            return;
        }


        // vvvvvvvvvvvvvvvvvvvvvvvvvvvv
        this._texture = value || Texture.EMPTY;
        // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


        this.cachedTint = 0xFFFFFF;

        this._textureID = -1;
        this._textureTrimmedID = -1;

        if (value)
        {
            // wait for the texture to load
            if (value.baseTexture.hasLoaded)
            {
                this._onTextureUpdate();
            }
            else
            {
                value.once('update', this._onTextureUpdate, this);
            }
        }
    }
```
