### ISSUE TITLE
BaseTexture.imageUrl deprecation warning on Pixi.js own code

### ISSUE THREAD

**Issue by fanjules** [pixijs/pixi.js#5632]
Triggered by a call to Renderer.resize()...

PixiJS Deprecation Warning: PIXI.BaseTexture.imageUrl property has been removed, use resource.urlDeprecated since v5.0.0
deprecation.js:45     at RenderTexture.destroy (http://localhost:1024/A_BAAMclient/pages/pixi5/pixi.js:13236:52)
    at FilterSystem.resize (http://localhost:1024/A_BAAMclient/pages/pixi5/pixi.js:15131:30)
    at Runner.emit (http://localhost:1024/A_BAAMclient/pages/pixi5/pixi.js:8991:24)
    at Renderer.resize (http://localhost:1024/A_BAAMclient/pages/pixi5/pixi.js:20793:30)
    at Object.renpixi.rpResize (http://localhost:1024/A_BAAMclient/pages/rp.js:288:15)
    at http://localhost:1024/A_BAAMclient/pages/main.js:210:17

Pixi 5.0.0
Chrome 74
Window 10 64bit

**Comment by bigtimebuddy** [comment]
Reproduces deprecation: https://pixiplayground.com/#/edit/PP6wCar~eanphFaVq41pZ

**Comment by bigtimebuddy** [comment]
Merged, thanks for reporting.
