### ISSUE TITLE
npm run build fails from fresh pull

### ISSUE THREAD

**Issue by mudcube** [pixijs/pixi.js#5931]
### Current Behavior
When running `npm run build` after `npm i` from a fresh pull on my system I run into an error. 

Any ideas what I might be doing wrong?

```
m:pixi.js m$ npm run build

> pixi.js-monorepo@ prebuild /Users/m/pixi.js
> npm run clean:build


> pixi.js-monorepo@ clean:build /Users/m/pixi.js
> rimraf "{bundles,packages,packages/canvas,packages/filters}/*/{lib,dist}"


> pixi.js-monorepo@ build /Users/m/pixi.js
> npm run build:dev


> pixi.js-monorepo@ build:dev /Users/m/pixi.js
> rollup -c


packages/constants/src/index.js → packages/constants/lib/constants.js, packages/constants/lib/constants.es.js...
created packages/constants/lib/constants.js, packages/constants/lib/constants.es.js in 73ms

packages/constants/src/index.js → packages/constants/dist/constants.js...
created packages/constants/dist/constants.js in 31ms

packages/math/src/index.js → packages/math/lib/math.js, packages/math/lib/math.es.js...
created packages/math/lib/math.js, packages/math/lib/math.es.js in 353ms

packages/math/src/index.js → packages/math/dist/math.js...
created packages/math/dist/math.js in 214ms

packages/polyfill/src/index.js → packages/polyfill/lib/polyfill.js, packages/polyfill/lib/polyfill.es.js...
created packages/polyfill/lib/polyfill.js, packages/polyfill/lib/polyfill.es.js in 59ms

packages/polyfill/src/index.js → packages/polyfill/dist/polyfill.js...
created packages/polyfill/dist/polyfill.js in 141ms

packages/runner/src/index.js → packages/runner/lib/runner.js, packages/runner/lib/runner.es.js...
created packages/runner/lib/runner.js, packages/runner/lib/runner.es.js in 54ms

packages/runner/src/index.js → packages/runner/dist/runner.js...
created packages/runner/dist/runner.js in 29ms

packages/settings/src/index.js → packages/settings/lib/settings.js, packages/settings/lib/settings.es.js...
created packages/settings/lib/settings.js, packages/settings/lib/settings.es.js in 38ms

packages/settings/src/index.js → packages/settings/dist/settings.js...
created packages/settings/dist/settings.js in 66ms

packages/unsafe-eval/src/index.js → packages/unsafe-eval/lib/unsafe-eval.js, packages/unsafe-eval/lib/unsafe-eval.es.js...
created packages/unsafe-eval/lib/unsafe-eval.js, packages/unsafe-eval/lib/unsafe-eval.es.js in 75ms

packages/unsafe-eval/src/bundle.js → packages/unsafe-eval/dist/unsafe-eval.js...
created packages/unsafe-eval/dist/unsafe-eval.js in 74ms

packages/ticker/src/index.js → packages/ticker/lib/ticker.js, packages/ticker/lib/ticker.es.js...
created packages/ticker/lib/ticker.js, packages/ticker/lib/ticker.es.js in 103ms

packages/ticker/src/index.js → packages/ticker/dist/ticker.js...
created packages/ticker/dist/ticker.js in 67ms

packages/utils/src/index.js → packages/utils/lib/utils.js, packages/utils/lib/utils.es.js...
created packages/utils/lib/utils.js, packages/utils/lib/utils.es.js in 124ms

packages/utils/src/index.js → packages/utils/dist/utils.js...
created packages/utils/dist/utils.js in 444ms

packages/display/src/index.js → packages/display/lib/display.js, packages/display/lib/display.es.js...
created packages/display/lib/display.js, packages/display/lib/display.es.js in 200ms

packages/display/src/index.js → packages/display/dist/display.js...
created packages/display/dist/display.js in 142ms

packages/core/src/index.js → packages/core/lib/core.js, packages/core/lib/core.es.js...
created packages/core/lib/core.js, packages/core/lib/core.es.js in 937ms

packages/core/src/index.js → packages/core/dist/core.js...
created packages/core/dist/core.js in 759ms

packages/mixin-get-child-by-name/src/index.js → packages/mixin-get-child-by-name/lib/mixin-get-child-by-name.js, packages/mixin-get-child-by-name/lib/mixin-get-child-by-name.es.js...
created packages/mixin-get-child-by-name/lib/mixin-get-child-by-name.js, packages/mixin-get-child-by-name/lib/mixin-get-child-by-name.es.js in 38ms

packages/mixin-get-child-by-name/src/index.js → packages/mixin-get-child-by-name/dist/mixin-get-child-by-name.js...
created packages/mixin-get-child-by-name/dist/mixin-get-child-by-name.js in 10ms

packages/mixin-get-global-position/src/index.js → packages/mixin-get-global-position/lib/mixin-get-global-position.js, packages/mixin-get-global-position/lib/mixin-get-global-position.es.js...
created packages/mixin-get-global-position/lib/mixin-get-global-position.js, packages/mixin-get-global-position/lib/mixin-get-global-position.es.js in 15ms

packages/mixin-get-global-position/src/index.js → packages/mixin-get-global-position/dist/mixin-get-global-position.js...
created packages/mixin-get-global-position/dist/mixin-get-global-position.js in 11ms

packages/canvas/canvas-display/src/index.js → packages/canvas/canvas-display/lib/canvas-display.js, packages/canvas/canvas-display/lib/canvas-display.es.js...
created packages/canvas/canvas-display/lib/canvas-display.js, packages/canvas/canvas-display/lib/canvas-display.es.js in 20ms

packages/canvas/canvas-display/src/index.js → packages/canvas/canvas-display/dist/canvas-display.js...
created packages/canvas/canvas-display/dist/canvas-display.js in 17ms

packages/extract/src/index.js → packages/extract/lib/extract.js, packages/extract/lib/extract.es.js...
created packages/extract/lib/extract.js, packages/extract/lib/extract.es.js in 42ms

packages/extract/src/index.js → packages/extract/dist/extract.js...
created packages/extract/dist/extract.js in 38ms

packages/loaders/src/index.js → packages/loaders/lib/loaders.js, packages/loaders/lib/loaders.es.js...
created packages/loaders/lib/loaders.js, packages/loaders/lib/loaders.es.js in 38ms

packages/loaders/src/index.js → packages/loaders/dist/loaders.js...
created packages/loaders/dist/loaders.js in 235ms

packages/mesh/src/index.js → packages/mesh/lib/mesh.js, packages/mesh/lib/mesh.es.js...
created packages/mesh/lib/mesh.js, packages/mesh/lib/mesh.es.js in 77ms

packages/mesh/src/index.js → packages/mesh/dist/mesh.js...
created packages/mesh/dist/mesh.js in 64ms

packages/particles/src/index.js → packages/particles/lib/particles.js, packages/particles/lib/particles.es.js...
created packages/particles/lib/particles.js, packages/particles/lib/particles.es.js in 92ms

packages/particles/src/index.js → packages/particles/dist/particles.js...
created packages/particles/dist/particles.js in 78ms

packages/sprite/src/index.js → packages/sprite/lib/sprite.js, packages/sprite/lib/sprite.es.js...
created packages/sprite/lib/sprite.js, packages/sprite/lib/sprite.es.js in 58ms

packages/sprite/src/index.js → packages/sprite/dist/sprite.js...
created packages/sprite/dist/sprite.js in 44ms

packages/canvas/canvas-extract/src/index.js → packages/canvas/canvas-extract/lib/canvas-extract.js, packages/canvas/canvas-extract/lib/canvas-extract.es.js...
created packages/canvas/canvas-extract/lib/canvas-extract.js, packages/canvas/canvas-extract/lib/canvas-extract.es.js in 23ms

packages/canvas/canvas-extract/src/index.js → packages/canvas/canvas-extract/dist/canvas-extract.js...
created packages/canvas/canvas-extract/dist/canvas-extract.js in 22ms

packages/canvas/canvas-renderer/src/index.js → packages/canvas/canvas-renderer/lib/canvas-renderer.js, packages/canvas/canvas-renderer/lib/canvas-renderer.es.js...
created packages/canvas/canvas-renderer/lib/canvas-renderer.js, packages/canvas/canvas-renderer/lib/canvas-renderer.es.js in 128ms

packages/canvas/canvas-renderer/src/index.js → packages/canvas/canvas-renderer/dist/canvas-renderer.js...
created packages/canvas/canvas-renderer/dist/canvas-renderer.js in 91ms

packages/filters/filter-alpha/src/index.js → packages/filters/filter-alpha/lib/filter-alpha.js, packages/filters/filter-alpha/lib/filter-alpha.es.js...
created packages/filters/filter-alpha/lib/filter-alpha.js, packages/filters/filter-alpha/lib/filter-alpha.es.js in 20ms

packages/filters/filter-alpha/src/index.js → packages/filters/filter-alpha/dist/filter-alpha.js...
created packages/filters/filter-alpha/dist/filter-alpha.js in 14ms

packages/filters/filter-blur/src/index.js → packages/filters/filter-blur/lib/filter-blur.js, packages/filters/filter-blur/lib/filter-blur.es.js...
created packages/filters/filter-blur/lib/filter-blur.js, packages/filters/filter-blur/lib/filter-blur.es.js in 49ms

packages/filters/filter-blur/src/index.js → packages/filters/filter-blur/dist/filter-blur.js...
created packages/filters/filter-blur/dist/filter-blur.js in 45ms

packages/filters/filter-color-matrix/src/index.js → packages/filters/filter-color-matrix/lib/filter-color-matrix.js, packages/filters/filter-color-matrix/lib/filter-color-matrix.es.js...
created packages/filters/filter-color-matrix/lib/filter-color-matrix.js, packages/filters/filter-color-matrix/lib/filter-color-matrix.es.js in 72ms

packages/filters/filter-color-matrix/src/index.js → packages/filters/filter-color-matrix/dist/filter-color-matrix.js...
created packages/filters/filter-color-matrix/dist/filter-color-matrix.js in 65ms

packages/filters/filter-displacement/src/index.js → packages/filters/filter-displacement/lib/filter-displacement.js, packages/filters/filter-displacement/lib/filter-displacement.es.js...
created packages/filters/filter-displacement/lib/filter-displacement.js, packages/filters/filter-displacement/lib/filter-displacement.es.js in 23ms

packages/filters/filter-displacement/src/index.js → packages/filters/filter-displacement/dist/filter-displacement.js...
created packages/filters/filter-displacement/dist/filter-displacement.js in 59ms

packages/filters/filter-fxaa/src/index.js → packages/filters/filter-fxaa/lib/filter-fxaa.js, packages/filters/filter-fxaa/lib/filter-fxaa.es.js...
created packages/filters/filter-fxaa/lib/filter-fxaa.js, packages/filters/filter-fxaa/lib/filter-fxaa.es.js in 17ms

packages/filters/filter-fxaa/src/index.js → packages/filters/filter-fxaa/dist/filter-fxaa.js...
created packages/filters/filter-fxaa/dist/filter-fxaa.js in 14ms

packages/filters/filter-noise/src/index.js → packages/filters/filter-noise/lib/filter-noise.js, packages/filters/filter-noise/lib/filter-noise.es.js...
created packages/filters/filter-noise/lib/filter-noise.js, packages/filters/filter-noise/lib/filter-noise.es.js in 19ms

packages/filters/filter-noise/src/index.js → packages/filters/filter-noise/dist/filter-noise.js...
created packages/filters/filter-noise/dist/filter-noise.js in 16ms

packages/accessibility/src/index.js → packages/accessibility/lib/accessibility.js, packages/accessibility/lib/accessibility.es.js...
created packages/accessibility/lib/accessibility.js, packages/accessibility/lib/accessibility.es.js in 61ms

packages/accessibility/src/index.js → packages/accessibility/dist/accessibility.js...
created packages/accessibility/dist/accessibility.js in 62ms

packages/app/src/index.js → packages/app/lib/app.js, packages/app/lib/app.es.js...
created packages/app/lib/app.js, packages/app/lib/app.es.js in 28ms

packages/app/src/index.js → packages/app/dist/app.js...
created packages/app/dist/app.js in 29ms

packages/graphics/src/index.js → packages/graphics/lib/graphics.js, packages/graphics/lib/graphics.es.js...
created packages/graphics/lib/graphics.js, packages/graphics/lib/graphics.es.js in 285ms

packages/graphics/src/index.js → packages/graphics/dist/graphics.js...
created packages/graphics/dist/graphics.js in 271ms

packages/mesh-extras/src/index.js → packages/mesh-extras/lib/mesh-extras.js, packages/mesh-extras/lib/mesh-extras.es.js...
created packages/mesh-extras/lib/mesh-extras.js, packages/mesh-extras/lib/mesh-extras.es.js in 72ms

packages/mesh-extras/src/index.js → packages/mesh-extras/dist/mesh-extras.js...
created packages/mesh-extras/dist/mesh-extras.js in 70ms

packages/mixin-cache-as-bitmap/src/index.js → packages/mixin-cache-as-bitmap/lib/mixin-cache-as-bitmap.js, packages/mixin-cache-as-bitmap/lib/mixin-cache-as-bitmap.es.js...
created packages/mixin-cache-as-bitmap/lib/mixin-cache-as-bitmap.js, packages/mixin-cache-as-bitmap/lib/mixin-cache-as-bitmap.es.js in 37ms

packages/mixin-cache-as-bitmap/src/index.js → packages/mixin-cache-as-bitmap/dist/mixin-cache-as-bitmap.js...
created packages/mixin-cache-as-bitmap/dist/mixin-cache-as-bitmap.js in 39ms

packages/sprite-animated/src/index.js → packages/sprite-animated/lib/sprite-animated.js, packages/sprite-animated/lib/sprite-animated.es.js...
created packages/sprite-animated/lib/sprite-animated.js, packages/sprite-animated/lib/sprite-animated.es.js in 35ms

packages/sprite-animated/src/index.js → packages/sprite-animated/dist/sprite-animated.js...
created packages/sprite-animated/dist/sprite-animated.js in 32ms

packages/sprite-tiling/src/index.js → packages/sprite-tiling/lib/sprite-tiling.js, packages/sprite-tiling/lib/sprite-tiling.es.js...
created packages/sprite-tiling/lib/sprite-tiling.js, packages/sprite-tiling/lib/sprite-tiling.es.js in 53ms

packages/sprite-tiling/src/index.js → packages/sprite-tiling/dist/sprite-tiling.js...
created packages/sprite-tiling/dist/sprite-tiling.js in 49ms

packages/spritesheet/src/index.js → packages/spritesheet/lib/spritesheet.js, packages/spritesheet/lib/spritesheet.es.js...
created packages/spritesheet/lib/spritesheet.js, packages/spritesheet/lib/spritesheet.es.js in 36ms

packages/spritesheet/src/index.js → packages/spritesheet/dist/spritesheet.js...
created packages/spritesheet/dist/spritesheet.js in 33ms

packages/canvas/canvas-particles/src/index.js → packages/canvas/canvas-particles/lib/canvas-particles.js, packages/canvas/canvas-particles/lib/canvas-particles.es.js...
created packages/canvas/canvas-particles/lib/canvas-particles.js, packages/canvas/canvas-particles/lib/canvas-particles.es.js in 27ms

packages/canvas/canvas-particles/src/index.js → packages/canvas/canvas-particles/dist/canvas-particles.js...
created packages/canvas/canvas-particles/dist/canvas-particles.js in 23ms

packages/canvas/canvas-sprite/src/index.js → packages/canvas/canvas-sprite/lib/canvas-sprite.js, packages/canvas/canvas-sprite/lib/canvas-sprite.es.js...
created packages/canvas/canvas-sprite/lib/canvas-sprite.js, packages/canvas/canvas-sprite/lib/canvas-sprite.es.js in 30ms

packages/canvas/canvas-sprite/src/index.js → packages/canvas/canvas-sprite/dist/canvas-sprite.js...
created packages/canvas/canvas-sprite/dist/canvas-sprite.js in 32ms

packages/text-bitmap/src/index.js → packages/text-bitmap/lib/text-bitmap.js, packages/text-bitmap/lib/text-bitmap.es.js...
created packages/text-bitmap/lib/text-bitmap.js, packages/text-bitmap/lib/text-bitmap.es.js in 70ms

packages/text-bitmap/src/index.js → packages/text-bitmap/dist/text-bitmap.js...
created packages/text-bitmap/dist/text-bitmap.js in 118ms

packages/text/src/index.js → packages/text/lib/text.js, packages/text/lib/text.es.js...
created packages/text/lib/text.js, packages/text/lib/text.es.js in 206ms

packages/text/src/index.js → packages/text/dist/text.js...
created packages/text/dist/text.js in 153ms

packages/canvas/canvas-graphics/src/index.js → packages/canvas/canvas-graphics/lib/canvas-graphics.js, packages/canvas/canvas-graphics/lib/canvas-graphics.es.js...
created packages/canvas/canvas-graphics/lib/canvas-graphics.js, packages/canvas/canvas-graphics/lib/canvas-graphics.es.js in 56ms

packages/canvas/canvas-graphics/src/index.js → packages/canvas/canvas-graphics/dist/canvas-graphics.js...
created packages/canvas/canvas-graphics/dist/canvas-graphics.js in 60ms

packages/canvas/canvas-mesh/src/index.js → packages/canvas/canvas-mesh/lib/canvas-mesh.js, packages/canvas/canvas-mesh/lib/canvas-mesh.es.js...
created packages/canvas/canvas-mesh/lib/canvas-mesh.js, packages/canvas/canvas-mesh/lib/canvas-mesh.es.js in 102ms

packages/canvas/canvas-mesh/src/index.js → packages/canvas/canvas-mesh/dist/canvas-mesh.js...
created packages/canvas/canvas-mesh/dist/canvas-mesh.js in 70ms

packages/canvas/canvas-sprite-tiling/src/index.js → packages/canvas/canvas-sprite-tiling/lib/canvas-sprite-tiling.js, packages/canvas/canvas-sprite-tiling/lib/canvas-sprite-tiling.es.js...
created packages/canvas/canvas-sprite-tiling/lib/canvas-sprite-tiling.js, packages/canvas/canvas-sprite-tiling/lib/canvas-sprite-tiling.es.js in 18ms

packages/canvas/canvas-sprite-tiling/src/index.js → packages/canvas/canvas-sprite-tiling/dist/canvas-sprite-tiling.js...
created packages/canvas/canvas-sprite-tiling/dist/canvas-sprite-tiling.js in 18ms

packages/interaction/src/index.js → packages/interaction/lib/interaction.js, packages/interaction/lib/interaction.es.js...
created packages/interaction/lib/interaction.js, packages/interaction/lib/interaction.es.js in 170ms

packages/interaction/src/index.js → packages/interaction/dist/interaction.js...
created packages/interaction/dist/interaction.js in 132ms

packages/prepare/src/index.js → packages/prepare/lib/prepare.js, packages/prepare/lib/prepare.es.js...
created packages/prepare/lib/prepare.js, packages/prepare/lib/prepare.es.js in 63ms

packages/prepare/src/index.js → packages/prepare/dist/prepare.js...
created packages/prepare/dist/prepare.js in 51ms

packages/canvas/canvas-text/src/index.js → packages/canvas/canvas-text/lib/canvas-text.js, packages/canvas/canvas-text/lib/canvas-text.es.js...
created packages/canvas/canvas-text/lib/canvas-text.js, packages/canvas/canvas-text/lib/canvas-text.es.js in 17ms

packages/canvas/canvas-text/src/index.js → packages/canvas/canvas-text/dist/canvas-text.js...
created packages/canvas/canvas-text/dist/canvas-text.js in 16ms

bundles/pixi.js/src/index.js → bundles/pixi.js/lib/pixi.js, bundles/pixi.js/lib/pixi.es.js...
created bundles/pixi.js/lib/pixi.js, bundles/pixi.js/lib/pixi.es.js in 126ms

bundles/pixi.js/src/index.js → bundles/pixi.js/dist/pixi.js...
created bundles/pixi.js/dist/pixi.js in 2.9s

packages/canvas/canvas-prepare/src/index.js → packages/canvas/canvas-prepare/lib/canvas-prepare.js, packages/canvas/canvas-prepare/lib/canvas-prepare.es.js...
created packages/canvas/canvas-prepare/lib/canvas-prepare.js, packages/canvas/canvas-prepare/lib/canvas-prepare.es.js in 109ms

packages/canvas/canvas-prepare/src/index.js → packages/canvas/canvas-prepare/dist/canvas-prepare.js...
created packages/canvas/canvas-prepare/dist/canvas-prepare.js in 18ms

bundles/pixi.js-legacy/src/index.js → bundles/pixi.js-legacy/lib/pixi-legacy.js, bundles/pixi.js-legacy/lib/pixi-legacy.es.js...
created bundles/pixi.js-legacy/lib/pixi-legacy.js, bundles/pixi.js-legacy/lib/pixi-legacy.es.js in 16ms

bundles/pixi.js-legacy/src/index.js → bundles/pixi.js-legacy/dist/pixi-legacy.js...
created bundles/pixi.js-legacy/dist/pixi-legacy.js in 3.2s

> pixi.js-monorepo@ postbuild /Users/m/pixi.js
> npm run types


> pixi.js-monorepo@ types /Users/m/pixi.js
> npm run types:legacy && npm run types:default


> pixi.js-monorepo@ types:legacy /Users/m/pixi.js
> mkdirp dist/types && jsdoc -c types/jsdoc-legacy.conf.json && node types/assemble pixi.js-legacy

There are no input files to process.
	fs.js:115
throw err;
^

Error: ENOENT: no such file or directory, open '/Users/m/pixi.js/dist/types/pixi.js-legacy.d.ts'
at Object.openSync (fs.js:436:3)
at Object.readFileSync (fs.js:341:35)
at Object.<anonymous> (/Users/m/pixi.js/types/assemble.js:19:17)
	at Module._compile (internal/modules/cjs/loader.js:688:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
	at Module.load (internal/modules/cjs/loader.js:598:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
	at Function.Module._load (internal/modules/cjs/loader.js:529:3)
	at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
	at startup (internal/bootstrap/node.js:285:19)
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! pixi.js-monorepo@ types:legacy: `mkdirp dist/types && jsdoc -c types/jsdoc-legacy.conf.json && node types/assemble pixi.js-legacy`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the pixi.js-monorepo@ types:legacy script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/m/.npm/_logs/2019-07-21T05_19_45_203Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! pixi.js-monorepo@ types: `npm run types:legacy && npm run types:default`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the pixi.js-monorepo@ types script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/m/.npm/_logs/2019-07-21T05_19_45_225Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! pixi.js-monorepo@ postbuild: `npm run types`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the pixi.js-monorepo@ postbuild script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /Users/m/.npm/_logs/2019-07-21T05_19_45_256Z-debug.log
```

### Environment

- **`pixi.js` version**: 5.1
- **Browser & Version**: Chrome 75
- **OS & Version**: MacOS 10.14.5

**Comment by bigtimebuddy** [comment]
What Node.js version are you running?

**Comment by mudcube** [comment]
@bigtimebuddy I was running `v10.14.1` so upgraded to `v10.16.0 LTS` but no dice :(

**Comment by yegao** [comment]
@mudcube I have the same problem
`> pixi.js-monorepo@ docs /Users/vvadmin/work/pixi.js
> mkdirp dist && jsdoc -c jsdoc.conf.json -R README.md

fs.js:130
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'fs'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:353:35)
    at loadSource (/Users/vvadmin/work/pixi.js/node_modules/requizzle/lib/loader.js:132:32)
    at Object.createWrapper (/Users/vvadmin/work/pixi.js/node_modules/requizzle/lib/loader.js:158:8)
    at Requizzle.requizzle (/Users/vvadmin/work/pixi.js/node_modules/requizzle/lib/requizzle.js:87:19)
    at infectProxy (/Users/vvadmin/work/pixi.js/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/Users/vvadmin/work/pixi.js/node_modules/requizzle/lib/loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/vvadmin/work/pixi.js/node_modules/jsdoc/lib/jsdoc/fs.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:945:30) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'fs'
}`

**Comment by yegao** [comment]
@mudcube I have a same problem,and I find the error throw in node_modules/requizzle/lib/requizzle.js:87:19
`function isNativeModule(targetPath, parentModule) {
	var lookupPaths = Module._resolveLookupPaths(targetPath, parentModule);
	if (lookupPaths && lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
		return true;
	}
	return false;
}`

**Comment by patwari** [comment]
> @mudcube I have a same problem,and I find the error throw in (node_modules/requizzle/lib/requizzle.js)
> 
> ```js
> function isNativeModule(targetPath, parentModule) {
> 	var lookupPaths = Module._resolveLookupPaths(targetPath, parentModule);
> 	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
> 		return true;
> 	}
> 	return false;
> }
> ```

You can update the version of JSDoc in package.json, and run npm install again: for example: 
		"jsdoc": "^3.6.3",

**Comment by killmecallic** [comment]
isNativeModule(targetPath, parentModule) {
	var lookupPaths = Module._resolveLookupPaths(targetPath, parentModule);
	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
		return true;
	}
	return false;

**Comment by killmecallic** [comment]
isNativeModule(targetPath, parentModule) {
	var lookupPaths = Module._resolveLookupPaths(targetPath, parentModule);
	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
		return true;
	}
	return false;[isNativeModule(targetPath, parentModule) { 	var lookupPaths = Module._resolveLookupPaths(targetPath, parentModule); 	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) { 		return true; 	} 	return false;](isNativeModule(targetPath, parentModule) { 	var lookupPaths = Module._resolveLookupPaths(targetPath, parentModule); 	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) { 		return true; 	} 	return false;)
