### ISSUE TITLE
Tests are failing on a clean clone of the `dev` branch

### ISSUE THREAD

**Issue by EvidentlyCube** [pixijs/pixi.js#6247]
I've cloned a fresh copy of the repository, `dev` branch. I first ran `npm i` then `npm run test`. There were five errors reported in the tests:

```
1) PIXI.BitmapFontLoader
       should properly register bitmap font having more than one texture:
     Uncaught Error: Texture Error: frame does not fit inside the base Texture dimensions: X: 2 + 19 = 21 > 1 and Y: 2 + 20 = 22 > 1
      at Texture.prototypeAccessors.frame.set (C:\Projects\Personal\JS\pixi.js\packages\core\lib\core.js:3671:19)
      at new Texture (C:\Projects\Personal\JS\pixi.js\packages\core\lib\core.js:3313:24)
      at Function.registerFont (C:\Projects\Personal\JS\pixi.js\packages\text-bitmap\lib\text-bitmap.js:635:26)
      at Function.parse (C:\Projects\Personal\JS\pixi.js\packages\text-bitmap\lib\text-bitmap.js:681:38)
      at completed (C:\Projects\Personal\JS\pixi.js\packages\text-bitmap\lib\text-bitmap.js:784:30)
      at MiniSignal.dispatch (C:\Projects\Personal\JS\pixi.js\node_modules\mini-signals\lib\mini-signals.js:93:18)
      at C:\Projects\Personal\JS\pixi.js\node_modules\resource-loader\dist\resource-loader.cjs.js:2262:34
      at next (C:\Projects\Personal\JS\pixi.js\node_modules\resource-loader\dist\resource-loader.cjs.js:53:9)
      at Loader.use (C:\Projects\Personal\JS\pixi.js\packages\text-bitmap\lib\text-bitmap.js:730:9)
      at C:\Projects\Personal\JS\pixi.js\node_modules\resource-loader\dist\resource-loader.cjs.js:2260:10

  2) PIXI.BitmapFontLoader
       should split fonts if page IDs are in chronological order:
     Uncaught Error: Texture Error: frame does not fit inside the base Texture dimensions: X: 2 + 19 = 21 > 1 and Y: 2 + 20 = 22 > 1
      at Texture.prototypeAccessors.frame.set (C:\Projects\Personal\JS\pixi.js\packages\core\lib\core.js:3671:19)
      at new Texture (C:\Projects\Personal\JS\pixi.js\packages\core\lib\core.js:3313:24)
      at Function.registerFont (C:\Projects\Personal\JS\pixi.js\packages\text-bitmap\lib\text-bitmap.js:635:26)
      at Function.parse (C:\Projects\Personal\JS\pixi.js\packages\text-bitmap\lib\text-bitmap.js:681:38)
      at completed (C:\Projects\Personal\JS\pixi.js\packages\text-bitmap\lib\text-bitmap.js:784:30)
      at MiniSignal.dispatch (C:\Projects\Personal\JS\pixi.js\node_modules\mini-signals\lib\mini-signals.js:93:18)
      at C:\Projects\Personal\JS\pixi.js\node_modules\resource-loader\dist\resource-loader.cjs.js:2262:34
      at next (C:\Projects\Personal\JS\pixi.js\node_modules\resource-loader\dist\resource-loader.cjs.js:53:9)
      at Loader.use (C:\Projects\Personal\JS\pixi.js\packages\text-bitmap\lib\text-bitmap.js:730:9)
      at C:\Projects\Personal\JS\pixi.js\node_modules\resource-loader\dist\resource-loader.cjs.js:2260:10

  3) PIXI.TextMetrics
       wordWrap without breakWords
         width should not be greater than wordWrapWidth with longText:
     AssertionError: expected 217.810546875 to be below 200
      at Context.<anonymous> (C:\Projects\Personal\JS\pixi.js\packages\text\test\TextMetrics.js:63:41)
      at callFn (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runnable.js:387:21)
      at Test.Runnable.run (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runnable.js:379:7)
      at Runner.runTest (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:535:10)
      at C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:653:12
      at next (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:447:14)
      at C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:457:7
      at next (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:362:14)
      at Immediate._onImmediate (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:425:5)
      at runCallback (timers.js:694:18)

  4) PIXI.TextMetrics
       whiteSpace `normal` without breakWords
         multiple spaces should be collapsed to 1 and but not newlines:

      5th line should not start with 3 spaces (1)
      + expected - actual

      -3
      +m

      at Context.<anonymous> (C:\Projects\Personal\JS\pixi.js\packages\text\test\TextMetrics.js:234:44)
      at callFn (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runnable.js:387:21)
      at Test.Runnable.run (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runnable.js:379:7)
      at Runner.runTest (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:535:10)
      at C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:653:12
      at next (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:447:14)
      at C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:457:7
      at next (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:362:14)
      at Immediate._onImmediate (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:425:5)
      at runCallback (timers.js:694:18)

  5) PIXI.TextMetrics
       whiteSpace `normal` with breakWords
         multiple spaces should be collapsed to 1 and but not newlines:

      5th line should not start with 3 spaces (1)
      + expected - actual

      -3
      +m

      at Context.<anonymous> (C:\Projects\Personal\JS\pixi.js\packages\text\test\TextMetrics.js:282:44)
      at callFn (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runnable.js:387:21)
      at Test.Runnable.run (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runnable.js:379:7)
      at Runner.runTest (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:535:10)
      at C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:653:12
      at next (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:447:14)
      at C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:457:7
      at next (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:362:14)
      at Immediate._onImmediate (C:\Projects\Personal\JS\pixi.js\node_modules\mocha\lib\runner.js:425:5)
      at runCallback (timers.js:694:18)
```

Reproduced with Node 10.16.3 x64. I tried to test on 12.13.1 amd 13.2.0 but in both cases a dependant library fails:
```
C:\Projects\Personal\JS\pixi.js\node_modules\requizzle\lib\requizzle.js:45
        if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {

TypeError: Cannot read property '0' of null
```

---

Is the five failing tests just the effect of dev branch being, well, dev branch so not necessarily always passing all the tests? Or is there possibly something in my environment that could be affecting that?

I ran the tests on Windows 10 x64 Home, Node 10.16.3 x64, on a fresh copy of the repository.

**Comment by ivanpopelyshev** [comment]
Known bug, but our tooling people don't use windows, I guess.  When I test stuff, i just ignore those 5 tests output, I'm that lazy.

**Comment by EvidentlyCube** [comment]
Interesting. Is there any point in me investigating this to see if maybe it can be fixed? Or was it attempted and failed in the past?

**Comment by themoonrat** [comment]
If you could investigate and find a fix, that'd be awesome :)

**Comment by EvidentlyCube** [comment]
I'll see what I can do :)
