### ISSUE TITLE
npm run types error

### ISSUE THREAD

**Issue by cjsjy123** [pixijs/pixi.js#6662]
> mkdirp dist/types && jsdoc -c types/jsdoc-legacy.conf.json && node types/assemble pixi.js-legacy

F:\test\node_modules\requizzle\lib\requizzle.js:45
        if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
                       ^

TypeError: Cannot read property '0' of null
    at isNativeModule (F:\node_modules\?[4mrequizzle?[24m\lib\requizzle.js:45:17)
    at Requizzle.requizzle (F:\node_modules\?[4mrequizzle?[24m\lib\requizzle.js:82:6)
    at infectProxy (F:\node_modules\?[4mrequizzle?[24m\lib\loader.js:82:28)
    at Module.targetModule.require (F:\node_modules\?[4mrequizzle?[24m\lib\loader.js:101:11)
?[90m    at require (internal/modules/cjs/helpers.js:72:18)?[39m
    at Object.<anonymous> (F:\node_modules\?[4mjsdoc?[24m\lib\jsdoc\fs.js:7:10)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1151:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)?[39m
    at Object.load (F:\node_modules\?[4mrequizzle?[24m\lib\loader.js:112:15)

**Comment by Zyie** [comment]
Hi, i ran into this issue a little while ago. You need to be using node v10 in order to build pixi.

I believe there is a pr open to update jsdocs so that the latest versions of node will work

**Comment by cjsjy123** [comment]
@Zyie  thx!
